src/index.html
Вот обновлённый тестовый Pull Request
=> Тестовый Pull Request

src/sass/base/_container.scss, src/sass/main.scss
=> Add container props

package-lock.json, src/index.html, src/index.js, src/js/events-service.js, src/js/refs.js, src/templates/eventTpl.hbs
Привет, Рома! 
Вот написан рабочий сервис по обращению на бекенд за событиями/концертами.
Я проверил, он работает , рендерится. Функции рендеринга в этом пул реквесте убрал, т.к. рисовать карточки будут другие одногруппники. Этот API имеет своеобразную структуру и параметры поиска. Я ещё буду улучшать этот класс. Но его уже можно использовать, делать следующие этапы работы.
=> Class for back end

src/images/svg/close.svg, src/images/svg/open.svg, src/index.html, src/index.js, src/js/data/countryList.json, src/js/search-fields.js, src/sass/base/_common.scss, src/sass/layouts/_search-fields.scss, src/sass/main.scss, src/sass/utils/_variables.scss, src/templates/countryList.hbs
Добавила:
1. Основные переменные по цвету
2. Дополнила базовые стили для сброса стилей по умолчанию для картинок, списков, ссылок
3. Добавила разметку в index.html по двум полям поиска
4. Добавила основную стилизация для полей поиска
5. Добавила основу для реализации логики по поиску страны
=> добавила основную разметку на поля для поиска

src/index.html, src/partials/footer.html, src/sass/layouts/_footer.scss
Как обойти заданные в _common.scss значения:
*,
*::before,
*::after {
box-sizing: border-box;
}
Это влияет на позиционирование текста при мобильной версии в футере. Если box-sizing:inherit, то проблема уходит.
=> positioning

package-lock.json, src/index.html, src/index.js, src/js/events-service.js, src/templates/eventTpl.hbs
На главной странице отображается загрузка популярных событий (по умолчанию только по США и Канаде) . Работает поиск по ключевому слову. Чуть позже будет добавлена обработка простейших ошибок ввода, с подключением библиотеки pnotify.
Для того, чтобы текст в карточках событий был виден (а то чёрное на черном не особо удобно :) ), я вписал в шаблон eventTpl.hbs классы, которые нашёл в папке со стилями. Кто работает со стилями карточек и выравниванием всей галереи - уже сами подправят.
=> Serch events by key word

src/index.html, src/templates/eventTpl.hbs
Стили в шаблоне eventTpl.hbs возвращены к старой версии, как прописывала Дина. Карточки не прямоугольные, а закруглены как по макету. Массив карточек загружается по центру страницы - в Димин грид partials/event-grid.html
=> Previous template

src/index.js
Сделана проверка ширины экрана. Если Tablet-версия, то грузим 21 картинку, для остальных версий грузим 20 картинок
=> Загрузка карточек для Tablet-версии

src/index.js, src/js/events-service.js, src/js/search-fields.js, src/sass/base/_container.scss, src/sass/layouts/_event-grid.scss
1) Сделана логика связи между инпутом, который ищет по ключевому слову и инпутом с выбранной страной.
2) Добавлено информационное сообщение, если по указанным параметрам запроса ничего не найдено.
3) Немного пришлось подправить разметку. И по спорному вопросу, что лучше использовать для отступа между галереей карточек и инпутом с выпадающим списком стран - однозначно использовать margin , иначе не возможно кликнуть и выбрать страну.
=> Search vers2

src/js/modal.js, src/sass/components/_modal-event.scss, src/sass/components/_modal.scss
1. устранено открытие окна на клик в пустые места галереи
2. перенесен код из modal-event.scss в modal.scss
3. подправлены стили окна
=> open-modal

package-lock.json, package.json, src/index.js, src/js/pagination.js
Changed pagination class getData method invocation. No need to add additional methods for search on input in the pagination class. This method is invoked in the index.js file now (line 38).
=> Refactor pagination class

src/index.html, src/js/modal.js, src/sass/components/_modal-event.scss, src/sass/components/_modal.scss, src/templates/modalEventTpl.hbs
=> corect-style

src/index.js, src/js/events-service.js
Рома! Смерджи , пожалуйста в ветку dev этот мой пулл реквест. Кто-то удалил строку, которая связывает наши с Аней классы поиска по слову и стране. Без неё Анин код не работает как надо. Спасибо!
=> Добавлена строка связи 2 классов

src/index.js, src/js/pagination.js
Add function to check proper q-ty of elements on page depending on User's viewport
=> Elements q-ty on Page for Pagination

src/index.html
добавляет подключение библиотеки simpleBar в index.html. Если не подключить, скрол не будет работать
=> добавляет подключение библиотеки simpleBar

src/index.js
Удалён повторяющийся обработчик из 48 строки в index.js
refs.searchInput.addEventListener('input', debounce(onInputChange, 500));
=> remove repeat call

src/index.html, src/index.js, src/js/events-service.js
Вариант с рабочей пагинацией на 5 страниц
=> Event service2

src/index.html, src/js/modal.js, src/sass/components/_modal.scss
1. в modal.js добавлен новый селектор (прячем/добавляем скроллап при открытии/закрытии)
2. переписаны css свойства для оверлея и окна
=> space-for-modal

src/index.html, src/sass/components/_scroll-bars.scss, src/sass/main.scss
Добавлены:
1. папка scroll-bars.scss и кастомные стили
2. import папки в main.scss
3. id на div. modal-overlay в html
=> scroll-bars

src/sass/components/_modal-event.scss, src/templates/modalEventTpl.hbs
подправлены стили иконки в модальном окне(размер на десктопе)
=> Correct modal event

src/js/data/team.js, src/partials/event-grid.html, src/sass/components/_decor-elements.scss, src/sass/components/_scroll-up.scss, src/sass/components/_theme-switch.scss, src/sass/layouts/_event-grid.scss, src/sass/layouts/_footer.scss, src/sass/layouts/_team-modal.scss, src/templates/eventTpl.hbs
-aded link into team modal-window;
-added cursor pointer to scroll-up button & button close the team modal-window;
-change color for location-icon in light theme;
-changed boldness in the footer lettering at light theme;
=> changes for lite theme

src/sass/components/_theme-switch.scss, src/sass/layouts/_event-grid.scss, src/sass/layouts/_pagination.scss
-added animation of pagination ;
-adapted the pagination styles for light theme.
=> animation of pagination

package-lock.json, src/index.html, src/js/modal.js, src/js/refs.js, src/sass/components/_modal.scss, src/sass/components/_scroll-bars.scss
final version:
1. перенесены refs в один файл
2. убраны комментарии в modal.js , modal.scss и html
3. добавлена анимация на закрытие  модального окна
=> modal-window

src/index.js
1) В файле events-service.js в 26 и 44 строках кто-то вписал информационные сообщения про то, что дынные не найдены. Реально оно не срабатывает, т.к. в events-service.js не подключена библиотека PNotify.js  . Ошибок не выкидывает, но и информационное уведомление не срабатывает. Можно просто закомментить. А если подключить сюда  библиотека PNotify, то будет перебивать Женину проверку на возврат пустого результата без событий.  
2) не уверен, что уведомления из п 1) вообще нужны, т.к. проверяем ошибку в Жениной функции  renderEventsList(events).
3) На данный момент, после всех обновлений функция renderEventsList хоть так и называется, но ничего реально не отрисовывает. Чтобы она соответствовала своему названию и реально что-то рендерила, я перенёс Димину функцию с вызовом пагинации (та в …
=> исправление ошибок
